# Generated by Django 5.0.6 on 2024-05-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_candidate_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_ID', models.CharField(max_length=100)),
                ('candidate_name', models.CharField(max_length=50)),
                ('pho', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
